Token 2022 support
Splyce-Finance/splyce-solana-vaults pull request #45
Opened 2024-12-05 11:53 UTC by vito-kovalione

2024-12-09 00:25 UTC, TonioMacaronio approved these changes

2024-12-09 00:36 UTC, TonioMacaronio requested changes

2024-12-09 00:36 UTC, TonioMacaronio commented on programs/tokenized_vault/src/utils/strategy.rs
> +    underlying_mint: AccountInfo<'a>,
You have to update call in `/tokenized_vault/src/instructions/direct_deposit.rs`, function `handle_direct_deposit`.
https://github.com/Splyce-Finance/splyce-solana-vaults/blob/38d537774a00d0962a14ff840ba48d2d92b832b8/programs/tokenized_vault/src/instructions/direct_deposit.rs#L97

2024-12-09 09:07 UTC, codinghistorian commented on programs/tokenized_vault/src/utils/strategy.rs
> +    underlying_mint: AccountInfo<'a>,
https://github.com/Splyce-Finance/splyce-solana-vaults/blob/38d537774a00d0962a14ff840ba48d2d92b832b8/programs/tokenized_vault/src/instructions/direct_deposit.rs#L87

transfer as well also needs additional mint arg

2024-12-09 13:24 UTC, codinghistorian approved these changes

2024-12-10 10:09 UTC, TonioMacaronio approved these changes

2024-12-10 10:09 UTC, merged